package Interfacez;

import javax.swing.JOptionPane;

public class Administrar_Vendedores extends javax.swing.JFrame {
    
    Inicio_Sesion ven = new Inicio_Sesion();
    Integer cedula;
    String nombre, apellido, tel, user, pwd, Conf;
    boolean adm;
    
    public Administrar_Vendedores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVendedores = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        btnBuscarVen = new javax.swing.JButton();
        btnGuardarVen = new javax.swing.JButton();
        btnModificarVen = new javax.swing.JButton();
        btnEliminarVen = new javax.swing.JButton();
        btnSalirVen = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combRoll = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmPwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel1.setText("CEDULA:");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel2.setText("NOMBRES");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel3.setText("APELLIDOS");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel4.setText("TELEFONO");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel5.setText("USUARIO");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel6.setText("CONTRASEÑA");

        lblVendedores.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        lblVendedores.setText("VENDEDORES");
        lblVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVendedoresMouseClicked(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtUser.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtPwd.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        btnBuscarVen.setText("BUSCAR");
        btnBuscarVen.setFocusPainted(false);
        btnBuscarVen.setFocusable(false);
        btnBuscarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVenActionPerformed(evt);
            }
        });

        btnGuardarVen.setText("GUARDAR");
        btnGuardarVen.setFocusPainted(false);
        btnGuardarVen.setFocusable(false);
        btnGuardarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVenActionPerformed(evt);
            }
        });

        btnModificarVen.setText("MODIFICAR");
        btnModificarVen.setFocusPainted(false);
        btnModificarVen.setFocusable(false);
        btnModificarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVenActionPerformed(evt);
            }
        });

        btnEliminarVen.setText("ELIMINAR");
        btnEliminarVen.setFocusPainted(false);
        btnEliminarVen.setFocusable(false);
        btnEliminarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVenActionPerformed(evt);
            }
        });

        btnSalirVen.setText("SALIR");
        btnSalirVen.setFocusPainted(false);
        btnSalirVen.setFocusable(false);
        btnSalirVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVenActionPerformed(evt);
            }
        });

        txtCedula.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel7.setText("ROLL");

        combRoll.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR", "1-ADMINISTRADOR", "2-VENDEDOR" }));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel8.setText("CONFIRMAR CONTRASEÑA");

        txtConfirmPwd.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btnBuscarVen))
                            .addComponent(txtConfirmPwd)
                            .addComponent(combRoll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnGuardarVen)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarVen)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarVen)
                        .addGap(24, 24, 24)
                        .addComponent(btnSalirVen)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVendedores)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarVen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVen)
                    .addComponent(btnModificarVen)
                    .addComponent(btnEliminarVen)
                    .addComponent(btnSalirVen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVenActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirVenActionPerformed

    private void btnGuardarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVenActionPerformed
        try {
            cedula = Integer.parseInt(txtCedula.getText());
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            tel = txtTelefono.getText();
            user = txtUser.getText();
            pwd = txtPwd.getText();
            Conf = txtConfirmPwd.getText();
            String roll = (String) combRoll.getSelectedItem();
            
            if (pwd.equals(Conf)) {
                if (!"SELECCIONAR".equals(roll)) {
                    switch (roll) {
                        case "1-ADMINISTRADOR":
                            adm = true;
                            ven.list.insertarcola(cedula, nombre, apellido, tel, user, pwd, adm);
                            ven.list.guardar_datos();
                            JOptionPane.showMessageDialog(null, "Se ha guardado de manera exitosa");
                            limpiar();
                            break;
                        case "2-VENDEDOR":
                            adm = false;
                            ven.list.insertarcola(cedula, nombre, apellido, tel, user, pwd, adm);
                            ven.list.guardar_datos();
                            JOptionPane.showMessageDialog(null, "Se ha guardado de manera exitosa");
                            limpiar();
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un roll");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, intente nuevamente");
                txtPwd.setText("");
                txtConfirmPwd.setText("");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite un numero de cedula valido");
        }

    }//GEN-LAST:event_btnGuardarVenActionPerformed

    private void btnBuscarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVenActionPerformed
        try {
            String recibido[] = null;
            cedula = Integer.parseInt(txtCedula.getText());
            recibido = ven.list.buscar(cedula);
            txtNombre.setText(recibido[0]);
            txtApellido.setText(recibido[1]);
            txtTelefono.setText(recibido[2]);
            txtUser.setText(recibido[3]);
            if ("true".equals(recibido[4])) {
                combRoll.setSelectedIndex(1);
            } else {
                combRoll.setSelectedIndex(2);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor digite un numero de cedula valido");
        }
        

    }//GEN-LAST:event_btnBuscarVenActionPerformed

    private void btnEliminarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVenActionPerformed
        try {
            int buscador = Integer.parseInt(txtCedula.getText());
            ven.list.eliminar(buscador);
            ven.list.guardar_datos();
            limpiar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor digite un numero de cedula valido");
        }

    }//GEN-LAST:event_btnEliminarVenActionPerformed

    private void btnModificarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVenActionPerformed
        try {
            String roll = (String) combRoll.getSelectedItem();
            
            int busc = Integer.parseInt(txtCedula.getText());
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            tel = txtTelefono.getText();
            user = txtUser.getText();
            pwd = txtPwd.getText();
            
            if (!"SELECCIONAR".equals(roll)) {
                switch (roll) {
                    case "1-ADMINISTRADOR":
                        adm = true;
                        
                        ven.list.modificar(busc, nombre, apellido, tel, user, pwd, adm);
                        ven.list.guardar_datos();
                        limpiar();
                        break;
                    case "2-VENDEDOR":
                        adm = false;
                        ven.list.modificar(busc, nombre, apellido, tel, user, pwd, adm);
                        ven.list.guardar_datos();
                        limpiar();
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un roll");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor digite un numero de cedula valido");
        }
        

    }//GEN-LAST:event_btnModificarVenActionPerformed

    private void lblVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendedoresMouseClicked
        ven.list.despliegaLista();
    }//GEN-LAST:event_lblVendedoresMouseClicked
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrar_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrar_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrar_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrar_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrar_Vendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVen;
    public javax.swing.JButton btnEliminarVen;
    public javax.swing.JButton btnGuardarVen;
    public javax.swing.JButton btnModificarVen;
    public javax.swing.JButton btnSalirVen;
    public javax.swing.JComboBox combRoll;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel lblVendedores;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JPasswordField txtConfirmPwd;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JPasswordField txtPwd;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {
        
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtUser.setText("");
        txtPwd.setText("");
        txtConfirmPwd.setText("");
        combRoll.setSelectedIndex(0);
    }
    
}
