//
package Interfacez;

import Listas_Conductores.Lista_Conductores;
import javax.swing.JOptionPane;

public class Administrar_Conductores extends javax.swing.JFrame {

    Lista_Conductores list_Con = new Lista_Conductores();
    int cedula, num;
    String nomb, apell, tel, rh, placa;

    public Administrar_Conductores() {
        initComponents();
        this.setLocationRelativeTo(null);
        list_Con.cargar_datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtTelefono_Con = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarCon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnGuardarCon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnModificarCon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarCon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSalirCon = new javax.swing.JButton();
        txtCedula_Con = new javax.swing.JTextField();
        txtApellido_Con = new javax.swing.JTextField();
        txtNombre_Con = new javax.swing.JTextField();
        txtRH_Con = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVehiculo_Con = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel8.setText("CONDUCTORES");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        txtPlaca.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtTelefono_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel1.setText("CEDULA:");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel2.setText("NOMBRES");

        btnBuscarCon.setText("BUSCAR");
        btnBuscarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel3.setText("APELLIDOS");

        btnGuardarCon.setText("GUARDAR");
        btnGuardarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel4.setText("TELEFONO");

        btnModificarCon.setText("MODIFICAR");
        btnModificarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarConActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel5.setText("# DE VEHICULO");

        btnEliminarCon.setText("ELIMINAR");
        btnEliminarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel6.setText("TIPO DE SANGRE");

        btnSalirCon.setText("SALIR");
        btnSalirCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirConActionPerformed(evt);
            }
        });

        txtCedula_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtApellido_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtNombre_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        txtRH_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel7.setText("PLACA");

        txtVehiculo_Con.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono_Con)
                                    .addComponent(txtApellido_Con)
                                    .addComponent(txtNombre_Con)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCedula_Con, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addGap(14, 14, 14)
                                        .addComponent(btnBuscarCon)))))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnGuardarCon)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarCon)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCon)
                                .addGap(58, 58, 58)
                                .addComponent(btnSalirCon))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtVehiculo_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRH_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(txtNombre_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtApellido_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtTelefono_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRH_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtVehiculo_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCon)
                    .addComponent(btnModificarCon)
                    .addComponent(btnEliminarCon)
                    .addComponent(btnSalirCon))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConActionPerformed
        String recibidos[] = null;

        try {
            int busc = Integer.parseInt(txtCedula_Con.getText());
            recibidos = list_Con.buscar(busc);
            txtNombre_Con.setText(recibidos[0]);
            txtApellido_Con.setText(recibidos[1]);
            txtTelefono_Con.setText(recibidos[2]);
            txtRH_Con.setText(recibidos[3]);
            txtPlaca.setText(recibidos[4]);
            txtVehiculo_Con.setText(recibidos[5]);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor rellene el campo cedula de manera correcta");
        }

    }//GEN-LAST:event_btnBuscarConActionPerformed

    private void btnGuardarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConActionPerformed
        try {
            cedula = Integer.parseInt(txtCedula_Con.getText());

            nomb = txtNombre_Con.getText();
            apell = txtApellido_Con.getText();
            tel = txtTelefono_Con.getText();
            rh = txtRH_Con.getText();
            placa = txtPlaca.getText();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Por favor rellene el campo de cedula correctamente");

        }

        try {

            num = Integer.parseInt(txtVehiculo_Con.getText());

            list_Con.insertarcola(cedula, nomb, apell, tel, rh, placa, num);
            list_Con.guardar_datos();
            JOptionPane.showMessageDialog(null, "Se guardo el conductor con exito");
            limpiar();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Por favor rellene el campo del numero del vehiculo correctamente");

        }


    }//GEN-LAST:event_btnGuardarConActionPerformed

    private void btnSalirConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirConActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirConActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        list_Con.despliegaLista();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnModificarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarConActionPerformed
        try {

            int busc = Integer.parseInt(txtCedula_Con.getText());

            nomb = txtNombre_Con.getText();
            apell = txtApellido_Con.getText();
            tel = txtTelefono_Con.getText();
            rh = txtRH_Con.getText();
            placa = txtPlaca.getText();
            num = Integer.parseInt(txtVehiculo_Con.getText());

            list_Con.modificar(busc, nomb, apell, tel, rh, placa, num);
            list_Con.guardar_datos();
            JOptionPane.showMessageDialog(null, "Se ha modificado el conductor correctamente");
            limpiar();
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Por favor verifique los campos e intente nuevamente");

        }

    }//GEN-LAST:event_btnModificarConActionPerformed

    private void btnEliminarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConActionPerformed
        try {
            int busc = Integer.parseInt(txtCedula_Con.getText());
            list_Con.eliminar(busc);
            list_Con.guardar_datos();
            limpiar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente el campo cedula");
        }
    }//GEN-LAST:event_btnEliminarConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrar_Conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrar_Conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrar_Conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrar_Conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrar_Conductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCon;
    public javax.swing.JButton btnEliminarCon;
    public javax.swing.JButton btnGuardarCon;
    public javax.swing.JButton btnModificarCon;
    public javax.swing.JButton btnSalirCon;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txtApellido_Con;
    public javax.swing.JTextField txtCedula_Con;
    public javax.swing.JTextField txtNombre_Con;
    public javax.swing.JTextField txtPlaca;
    public javax.swing.JTextField txtRH_Con;
    public javax.swing.JTextField txtTelefono_Con;
    public javax.swing.JTextField txtVehiculo_Con;
    // End of variables declaration//GEN-END:variables
public void limpiar() {
        txtCedula_Con.setText("");
        txtNombre_Con.setText("");
        txtApellido_Con.setText("");
        txtTelefono_Con.setText("");
        txtRH_Con.setText("");
        txtPlaca.setText("");
        txtVehiculo_Con.setText("");
    }
}
